apiVersion: v1
kind: Service
metadata:
  name: maria
  labels:
    app:
      maria
spec:
  selector:
    app: maria
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: maria
      port: 3306
      targetPort: 3306
      nodePort: 30004

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: maria
spec:
  selector:
    matchLabels:
      app: maria
  serviceName: "maria"
  replicas: 1
  template:
    metadata:
      labels:
        app: maria
    spec:
      containers:
      - name: maria
        image: mariadb:10.4
        ports:
        - containerPort: 3306
          name: maria
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        # - name: initdb
        #   mountPath: /docker-entrypoint-initdb.d
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              configMapKeyRef:
                name: maria-configmap
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_USER
            valueFrom: 
              configMapKeyRef:
                name: maria-configmap
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: maria-configmap
                key: MYSQL_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: maria-configmap
                key: MYSQL_DATABASE


      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mariaclaim
      # - name: initdb
      #   hostPath: 
      #     path: /home/devops/chartissimo/mariadb/initdb
      #     type: Directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariaclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maria-configmap
data:
  MYSQL_ROOT_PASSWORD: "admin"
  MYSQL_USER: "chart"
  MYSQL_PASSWORD: "chart"
  MYSQL_DATABASE: "chartissimo"
