apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: chartissimo
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      nodePort: 30000
