apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: chartissimo
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: auth
      port: 6000
      targetPort: 6000
      nodePort: 30006