apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: chartissimo
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: gateway
      port: 8080
      targetPort: 8080
      nodePort: 30007