apiVersion: v1
kind: Service
metadata:
  name: java-user
spec:
  selector:
    app: chartissimo
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: java-user
      port: 8080
      targetPort: 8080
      nodePort: 30005