apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app:
      mongo
spec:
  selector:
    app: mongo
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: mongo
      port: 27017
      targetPort: 27017
      nodePort: 30003