apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: chartissimo
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: api
      port: 5000
      targetPort: 5000
      nodePort: 30001